# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57ee4a69ad4d70b6c4b1fb6904d5c59f94c728f4d69b058eb7213fde9c5b7b1690c21c109d2cb71203193a2754b2cbb6682fa95566a8c5773eaf364d7417586d

test:
  secret_key_base: 671ee871038fa2a8683d381ef6803cefb18fc950a3271a6b5c21d3d4e266984a216476fec68b678fa4063b52d9a04a78c1ce0f0c0330e6d98355bb66ce6efbf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
